### ISSUE TITLE
Divulgar o site da PyNE 2024

### ISSUE THREAD

**Issue by itepifanio** [pythonNordeste/organizacao-pyne-2024#1]
Criar uma arte, e realizar a comunicação nas redes sociais da Python Nordeste, para divulgar o site da PyNE 2024

Para concluir essa issue deve-se:

- [x] Gerar o texto para as redes sociais
- [x] Gerar a arte para divulgação
- [x] Publicar nas redes sociais da Python Nordeste

**Comment by itepifanio** [comment]
@lucasleninsa modifiquei a issue #3 para uma data mais afastada. Acho que temos que focar em, além de modificar o ícone e capa das redes sociais, realizar um post mostrando a identidade visual da Python Nordeste e com um texto introduzindo o site. Você conseguiria fazer a arte dessa postagem até dia 11 de dezembro? A ideia é colocar nas redes sociais e apresentar que a Python Nordeste 2024 vai acontecer nos dias 09, 10 e 11 de agosto de 2024 e que será em Natal.

A arte pode ser no modelo da seguinte: https://www.instagram.com/p/CrbH25FrYRM/

**Comment by lucasleninsa** [comment]
Olá, segue o link com as postagens: https://drive.google.com/drive/folders/1pcXEPeiTZlcDjy_-S7ZWAPWYcDafFP03
