### ISSUE TITLE
Gerar logo para redes sociais em png

### ISSUE THREAD

**Issue by itepifanio** [pythonNordeste/organizacao-pyne-2024#10]
Essa issue é resolvida quando:

- [x] Uma logo png é gerada para os perfis das redes sociais: twitter, linkedin, telegram, instagram e facebook

**Comment by lucasleninsa** [comment]
Olá, segue o link: https://drive.google.com/drive/u/0/folders/1dGAQ_mT8cIk_yjN1CHu6UkJyU9bnkkp6

**Comment by itepifanio** [comment]
> Olá, segue o link: https://drive.google.com/drive/u/0/folders/1dGAQ_mT8cIk_yjN1CHu6UkJyU9bnkkp6

Valeu, Lucas. Marcando a issue como resolvida!
