### ISSUE TITLE
Resgatar dados das redes sociais

### ISSUE THREAD

**Issue by itepifanio** [pythonNordeste/organizacao-pyne-2024#105]
- [x] Nº de visualizações no instagram (de 13/08/2024 - 30 dias tivemos 56 mil visualizações)
- [x] Nº de acessos no google analytics (site)
- [ ] Nº de visualizações no telegram
- [x] Nº de visualizações no twitter
- [x] Nº de visualizações no linkedin
- [x] Nº de inscritos
- [x] Nº de participantes

**Comment by emillyhorta** [comment]
**LinkedIn**

Ultimos 30 dias

Visualizações da página - 210.
Visitantes únicos - 99
Total de seguidores - 1.101
Novos seguidores - 68

**Twitter**

Nos últimos 30 dias

Em média 395 visualizações

**Inscritos no evento**

Tivemos 421 inscritos 

**Participantes no evento**

 tendo 73% de participação, 310 credenciados;


**Google Analytics - Site**

Nos últimos 30 dias - ainda n temos essa informação

**Instagram**

Nos últimos 30 dias

56.920 visualizações
Visualizações nas postagens, entre 1.300 a 2.500
Seguidores - aumentou 3,5 %

**Comment by itepifanio** [comment]
@Emilly-horta  a gente conseguiria os dados retroativos dos últimos 365 dias? Seria o ideal, caso contrário esses números já devem ser suficientes para a edição 2025

Dos dados do site entre 2023-08-25 a 2024-08-25:

Número de usuários: 5,4 mil
Tempo médio de engajamento: 1m 02s
Total de acessos: 18334
Início de sessão: 13230
Scroll: 6379
Engajamentos na página: 5700

Usuário por país:
![image](https://github.com/user-attachments/assets/051c8b6e-2a7b-43ed-b1cc-11185895305b)

Usuários por SO:
![image](https://github.com/user-attachments/assets/e49f3e36-7cbe-438c-9372-7625748b5158)

![image](https://github.com/user-attachments/assets/e2f0ca29-e3b3-4bcb-850e-5b11a742fb75)

![image](https://github.com/user-attachments/assets/f41125c2-5c64-42d4-bd22-e4c75e27a047)

**Comment by emillyhorta** [comment]
Beleza, vou verificar

**Comment by emillyhorta** [comment]
essas métricas do telegram eu n sei informar.

**Comment by itepifanio** [comment]
@Emilly-horta revi algumas métricas e estou reportando o feedback para os patrocinadores com o seguinte texto:

- No evento tivemos 421 inscritos dos quais 310 fizeram checkin
- No linkedin acumulamos 39405 visualizações em nossas postagens durante o ano de 2024, dessas 1885 foram engajamento direto através de curtidas
- No instagram nos últimos 90 dias tivemos 82231 impressões em nossas postagens, alcançando um total de 8010 contas. Temos de seguidores no perfil o total de 4803 seguidores.
- Do twitter e telegram não conseguimos extrair muitas métricas, mas em específico do telegram nossos posts no canal da Python Brasil tem alcance de mais de 23600 contas e nosso grupo do telegram conta com 782 membros
- No nosso site alcançamos mais de 5,4 mil usuários com o tempo médio de engajamento de 1,02 minutos, sendo 18334 acessos
