### ISSUE TITLE
Elaboração de plano de postagens inicial

### ISSUE THREAD

**Issue by itepifanio** [pythonNordeste/organizacao-pyne-2024#11]
Elaboração de documento inicial com plano de postagens para dezembro de 2023 e janeiro de 2023. Datas importantes e prazos mais estruturados também pode ser adicionados ao plano.

Essa issue deve:

- [x] Gerar um documento no drive que descreva as postagens necessárias para uma comunicação efetiva com a comunidade
- [x] Discussão com a organização sobre o documento
- [x] Geração de issues para as equipes de design e comunicação

**Comment by itepifanio** [comment]
@elayni após gerar as novas issues fecha essa daqui por favor

**Comment by itepifanio** [comment]
@elayni já estamos com acesso as redes sociais. Atualizei o prazo da issue para o dia 17, se precisar de ajuda com as issues só falar.

**Comment by elayni** [comment]
@itepifanio pode me ajudar com as issues? A semana virou de cabeça pra baixo por aqui

**Comment by itepifanio** [comment]
@elayni movi a chamada de patrocinadores para a próxima semana, em vez de janeiro. 

Por favor revisa as datas sugeridas de cada issue e verifica se está tudo aqui.
