### ISSUE TITLE
Realizar curadoria das fotos do evento

### ISSUE THREAD

**Issue by itepifanio** [pythonNordeste/organizacao-pyne-2024#112]

**Comment by VictorBenoiston** [comment]
Ao meu ver, as imagens não vão contra nenhuma diretriz do CDC. Inclusive, um belo trabalho!

**Comment by deboraazevedo** [comment]
também revisei as fotos e nao encontrei nada que vá contra o CDC

**Comment by itepifanio** [comment]
Agradeço a curadoria @VictorBenoiston e @deboraazevedo irei seguir com as publicações da maioria das fotos no flickr #115
