### ISSUE TITLE
Elaborar orçamento de painel instagramável pro evento

### ISSUE THREAD

**Issue by itepifanio** [pythonNordeste/organizacao-pyne-2024#13]
Orçar um painel instagramável: estrutura + impressão. 

Esse orçamento é importante pois é onde vamos publicizar os patrocinadores e precisamos ter no evento. Podem ver diferentes tamanhos e diferentes fornecedores.

Essa issue será concluída quando tivermos uma tabela com valores de várias empresas. Na foto a seguir o painel da Python Nordeste 2023

![Image](https://github.com/pythonNordeste/organizacao-pyne-2024/assets/6730205/ccb26218-7da8-49b0-b76f-04de690e1ba1)

**Comment by emillyhorta** [comment]
Vou fazer um orçamento aqui. Qual o tamanho ideal do blackdrop?

**Comment by diegodiogenes** [comment]
@Emilly-horta o tamanho que estava sendo orçado foi o mesmo referente a PyNE 2023, segue a mensagem:

> A arte do backdrop  foi 5m x 2m
A arte do banner foi  80cm x 120cm
O backdrop foi confeccionado com 500 x 240 cm, em lona CBIO tamanho da lona são 2m40 cm e quando juntamos com a estruturas do ferro fica em 2m80cm. Mas para que não tivéssemos nenhum problema com o local reduzimos a lona para 2m.

**Comment by diegodiogenes** [comment]
Planilha com orçamentos: https://docs.google.com/spreadsheets/d/1N4SK3Wu_wX09vY9ndSUycZvNVBDdVEt0IEIgkBTadoI/edit?usp=sharing

**Comment by Emilly-horta** [comment]
R$960 5x2,40m com ilhóis e vulcanizada. Ilhóis é o que prende a lona na estrutura metalica

**Comment by emillyhorta** [comment]
certo.

**Comment by emillyhorta** [comment]
a estrutura em metalon 25x25 mm 5x2 m fica 1.600,00 
servço de montagem e desmontagem fica 400,00
lona bacdrop com ilhois 5x2 metros fica 800,00
banner 80x120 cm fica 80,00
total 2.880,00

Orçamento Vital gráfica
