### ISSUE TITLE
Relação de canais para divulgação do evento

### ISSUE THREAD

**Issue by jjpaulo2** [pythonNordeste/organizacao-pyne-2024#15]
> **Lista em construção**. Podem haver novas adições.

| Rede social | Nome | Contato | Comentário |
|-|-|-|-|
| Telegram | Canal Python Brasil | [@laenderoliveira](https://t.me/laenderoliveira) | Precisa entrar em contato pelo privado do Laender para fazer a divulgação no canal. | 
| Telegram | PUG Piauí | [@pugpi](https://t.me/pugpi) | Pode compartilhar no chat do grupo. | 
| Telegram | PUG Paraíba | [@pugpb](https://t.me/pugpb) | Pode compartilhar no chat do grupo. | 
| Telegram | PUG Maranhão | [@pugma](https://t.me/pugma) | Pode compartilhar no chat do grupo. | 
| Telegram | GruPy Bahia | [@grupyba](https://t.me/grupyba) | Pode compartilhar no chat do grupo. | 
| Telegram | PyLadies Brasil - Canal de Notícias | [@deboraazevedoo](https://t.me/pyladiesbrasil) | Débora consegue postar no canal. | 
| Telegram | PyLadies Brasil | [@deboraazevedoo](https://t.me/deboraazevedoo) | Pode compartilhar no chat do grupo | 
| Telegram | PUG Pernambuco | [@pugpe](https://t.me/pugpe) | Pode compartilhar no chat do grupo. |
| Telegram | PUG Sergipe | [@pugse](https://t.me/pugse) | Pode compartilhar no chat do grupo. |
| Telegram | Grupy Rio Grande do Norte | [@grupyrn](https://t.me/GrupyRN) | Pode compartilhar no chat do grupo.
| Telegram | PUG Ceará | [@patriciasilvarecife](https://t.me/patriciasilvarecife) | Patrícia pode compartilhar no chat do grupo. |
| Telegram | PyLadies Nordeste | [@patriciasilvarecife](https://t.me/patriciasilvarecife) | Patrícia pode compartilhar no chat do grupo. |

**Comment by deboraazevedo** [comment]
Eu consigo postar no canal Python Brasil, vou adicionar outros canais na lista

**Comment by PatriciaSilvaRecife** [comment]
Estou em débito. Tinha esquecido com esta coerência de final de ano. Perdão!!

Logo menos alimento aqui.

**Comment by PatriciaSilvaRecife** [comment]
Como as PyLadies estão no grupo da PyLadies Brasil e PyLadies Nordeste não coloquei o contato individual de cada grupo. Há não ser que seja necessário para formalizar a divulgação.

**Comment by itepifanio** [comment]
@PatriciaSilvaRecife você conseguiria verificar se a submissão de atividade foi compartilhada nesses canais? 
Vi que ela já foi encaminhada pro canal da Python Brasil, mas não vi nos demais canais.

**Comment by PatriciaSilvaRecife** [comment]
@itepifanio foram compartilhados nos demais canais.
