### ISSUE TITLE
Chamada inicial de submissão de palestras

### ISSUE THREAD

**Issue by itepifanio** [pythonNordeste/organizacao-pyne-2024#18]
O prazo dessa issue depende de #9 

Gerar texto e arte para chamada de submissões de atividades. 

- [x] Gerar o texto para as redes sociais
- [x] Gerar a arte para divulgação
- [x] Artigo do blog GruPy-RN
- [x] Publicar nas redes sociais da Python Nordeste

**Comment by lucasleninsa** [comment]
Segue o link: https://drive.google.com/drive/folders/13YjrBgnSXqf3jgvnZWLwvWbsonoxHxPF?usp=drive_link
