### ISSUE TITLE
Atualizar logo das redes sociais

### ISSUE THREAD

**Issue by itepifanio** [pythonNordeste/organizacao-pyne-2024#2]
Modificar o logo de todas as redes sociais para a PyNE 2024

- [x] Telegram
- [x] Instagram
- [x] Linkedin
- [x] Twitter

**Comment by itepifanio** [comment]
@cecivieira conseguiram resolver o acesso ao gerenciador de senhas? Gostaríamos de começar a atualizar as redes sociais com a carinha da edição 2024

**Comment by itepifanio** [comment]
@pythonNordeste/comunicacao-2023 a gente ainda está sem acesso as redes sociais, vocês conseguiriam atualizar a logo das redes sociais? A logo das redes sociais [pode ser acessada aqui](https://drive.google.com/file/d/1V9sPbScKFa6XnvvY0XY1F3olpb30Hctr/view?usp=sharing).

**Comment by cecivieira** [comment]
@itepifanio te enviei ao bitwarden. Estou configurando agora as coleções

**Comment by cecivieira** [comment]
@itepifanio caso você sinta falta de alguma credencial, dá um "oi" aqui

**Comment by itepifanio** [comment]
> @itepifanio te enviei ao bitwarden. Estou configurando agora as coleções

@cecivieira valeu, recebi o convite e aceitei. Acredito que você ainda precise confirmar os meus acessos, o vault da PyNE não apareceu para mim.

```
The invitation process to an Organization is three steps:

1. Invite the user: https://bitwarden.com/help/managing-users/#invite
2. Acceptance of the invitation by the user.
3. Confirmation of the user by an Admin. This is an essential step as it 
completes the public-key exchange, allowing for the sharing of encrypted 
information: https://bitwarden.com/help/managing-users/#confirm

An organization admin can confirm a new user by logging into their Web Vault
 (https://vault.bitwarden.com/) and go to 
Organizations > [Your Organization Name] > Members tab 
and use the 3 dots options menu to select Confirm.
```

**Comment by cecivieira** [comment]
@itepifanio confirmei
Vê se funcionou

**Comment by itepifanio** [comment]
> @itepifanio confirmei Vê se funcionou

Tudo certo @cecivieira. Agora só preciso coordenar o acesso do email, via autenticação de dois fatores
