### ISSUE TITLE
Orçamento de equipe de limpeza

### ISSUE THREAD

**Issue by itepifanio** [pythonNordeste/organizacao-pyne-2024#22]
Realizar orçamento de equipes de limpeza para o auditório da escola da governadoria nos dias 10 e 11 de agosto.

O espaço comporta 700 pessoas, mas não temos a dimensão em metros quadrados.

**Comment by itepifanio** [comment]
@allythy está verificando se a equipe de limpeza da escola da governadoria aceita o pagamento via CNPJ

**Comment by allythy** [comment]
Para os dois dias fica R$960, porque são três pessoas e diária de cada um deles é R$160

**Comment by allythy** [comment]
> @allythy está verificando se a equipe de limpeza da escola da governadoria aceita o pagamento via CNPJ

Eles não tem CNPJ para receber o pagamento.

**Comment by allythy** [comment]
@cecivieira o pessoal não tem CNPJ para receber o pagamento, tem como transferir para pessoal física?

**Comment by cecivieira** [comment]
Não é possível realizar pagamento para CPF.
Nesses casos, indicamos que a pessoa procure a prefeitura da cidade para emissão da nota fiscal como autônomo.
Secretaria responsável: https://www.natal.rn.gov.br/semut/
