### ISSUE TITLE
Orçamento de ecobags

### ISSUE THREAD

**Issue by itepifanio** [pythonNordeste/organizacao-pyne-2024#23]
Geralmente é mais barato comprar o tecido e mandar custurar, mas é bom verificar também o preço de quem faz esse tipo de serviço.

Seriam em torno de 450 ecobags de tamanho pelo menos 30 de altura e 25 de altura ou variações desses tamanhos

**Comment by emillyhorta** [comment]
30 de altura e 25 de largura né?

**Comment by Ryllari** [comment]
Criei uma planilha na pasta de Orçamentos da Organização
