### ISSUE TITLE
Acesso ao gerenciador de senhas

### ISSUE THREAD

**Issue by itepifanio** [pythonNordeste/organizacao-pyne-2024#26]
Dar acesso ao @allythy e @Ryllari

**Comment by cecivieira** [comment]
convites enviados

**Comment by allythy** [comment]
Podeira habilitar o meu acesso ao gerenciador de senhas, por favor. @cecivieira

**Comment by cecivieira** [comment]
@allythy @Ryllari conclui o acesso de vocês ao bitwarden. Caso haja algum ajuste a ser realizado, reabre essa issue.
