### ISSUE TITLE
Orçamento de crachá pro evento

### ISSUE THREAD

**Issue by itepifanio** [pythonNordeste/organizacao-pyne-2024#28]

**Comment by emillyhorta** [comment]
Orçamento na vital gráfica 

Produto: Cracha em PVC + Porta cracha + Cordão personalizado

Valor normal R$30, nessa quantidade conseguimos fazer R$20 a und

[17:41, 01/02/2024] +55 84 8800-7493: A arte e montagem está inclusa
[17:41, 01/02/2024] +55 84 8800-7493: Comercial:
Se for mudar de um para o outro, precisamos da lista em excel com nome, e se tiver foto, a foto de cada pessoa
[17:42, 01/02/2024] +55 84 8800-7493: Comercial:
A arte criamos tanto do cracha quanto do cordão

Prazo: 4 dias úteis

[Orcamento_149_Emilly_Horta.pdf](https://github.com/pythonNordeste/organizacao-pyne-2024/files/14130792/Orcamento_149_Emilly_Horta.pdf)
