### ISSUE TITLE
Orçamento de stickers

### ISSUE THREAD

**Issue by itepifanio** [pythonNordeste/organizacao-pyne-2024#29]

**Comment by Ryllari** [comment]
Em 2021 fizemos com a Nerd Stickers, eles possuem um modelo de cartela de adesivos que pode sair mais em conta.

Fazendo um orçamento padrão no site, pensando em 500 unidades, a cartela 10x15 saiu por R$ 2,62 a unidade. A gente pode ver se ainda dá pra baratear isso em contato com eles.
<img width="1323" alt="Captura de Tela 2024-01-31 às 08 49 38" src="https://github.com/pythonNordeste/organizacao-pyne-2024/assets/15248191/235fc67c-65d6-4e29-8240-c3491795c0ce">

**Comment by itepifanio** [comment]
@Ryllari o GruPy tinha conversado com o [Rei dos Stickers](https://reidosticker.com.br/) também, eles são de Recife. Eles mandaram uns exemplares pra gente e os modelos deles são de qualidade similar ao nerd stickers e eles ainda tem um cupom de 10% no site para compras acima de 600 reais. O fosco emborrachado deles é um pouco mais escuro que a do Nerd Stickers.

![Screenshot from 2024-01-31 09-44-25](https://github.com/pythonNordeste/organizacao-pyne-2024/assets/6730205/4823f739-fa38-4599-9785-2baf9cb1d2cc)

**Comment by emillyhorta** [comment]
Rei dos Stickers tá saindo mais barato. Fecha nesse valor mesmo de 1.140?

**Comment by itepifanio** [comment]
> Rei dos Stickers tá saindo mais barato. Fecha nesse valor mesmo de 1.140?

@Emilly-horta a ideia por enquanto é ir adicionando esses dados no drive mesmo. Fechar a gente só vai fazer depois que tivermos os dinheiros dos patrocinadores/ingressos em mões

**Comment by emillyhorta** [comment]
Entendi! Onde eu posso add os orçamentos no drive?

**Comment by itepifanio** [comment]
@Emilly-horta desculpa a demora em responder, [segue o link](https://docs.google.com/spreadsheets/d/1w5UA-W_7vOqPPqGoFV6cTqub7jAcAfBNatbizUMtJsI/edit?usp=drive_link)

**Comment by emillyhorta** [comment]
de boas
