### ISSUE TITLE
Chamada de patrocinadores

### ISSUE THREAD

**Issue by itepifanio** [pythonNordeste/organizacao-pyne-2024#3]
Criar uma arte, e realizar a comunicação nas redes sociais da Python Nordeste, para chamada de patrocinadores.

Para concluir essa issue deve-se:
- [x] Gerar o texto para as redes sociais
- [x] Gerar a arte para divulgação
- [x] Publicar nas redes sociais da Python Nordeste

**Comment by biancapinho** [comment]
Arte concluída
- Inseri o texto na arte apenas para facilitar no design e na diagramação
- Usei como base o plano de patrocínio e inseri os assets que representa cada cota para compor a imagem

![Chamada de patrocinadores](https://github.com/pythonNordeste/organizacao-pyne-2024/assets/153767055/b782eab9-c321-496d-8f29-7839bd93e681)

**Comment by itepifanio** [comment]
Obrigado pela ajuda @biancapinho!

Marcando essa issue como resolvida.
