### ISSUE TITLE
Contato com a Evolux

### ISSUE THREAD

**Issue by itepifanio** [pythonNordeste/organizacao-pyne-2024#36]

**Comment by itepifanio** [comment]
Evolux confirmou interesse na cota cobre, estamos na espera da emissão da Nota Fiscal por parte da APyB

**Comment by itepifanio** [comment]
@cecivieira te adicionei como membro dessa issue para acompanhar a emissão da nota fiscal

**Comment by cecivieira** [comment]
@itepifanio acabei de emitir a nota. Por favor, verifica o recebimento.

**Comment by itepifanio** [comment]
@cecivieira confirmo recebimento, obrigado!
