### ISSUE TITLE
Adicionar organizadores

### ISSUE THREAD

**Issue by itepifanio** [pythonNordeste/organizacao-pyne-2024#4]
Adicionar os seguintes perfis a organização PyNE 2024

@matheusmouraa
@Ryllari 
@PatriciaSilvaRecife 
@elayni
@gabicavalcante
@deboraazevedo
@Emilly-horta 
@JordyAraujo
@diegodiogenes
@exageraldo
@alvarofpp
@MayraPerpetua
@rioribeirods
@Cleocelestino

**Comment by cecivieira** [comment]
Todos foram adicionados como membras do time @pythonNordeste/pyne2024 
Os convites foram enviados por e-mail e precisam ser aceitos. Caso alguém não encontre o e-mail de convite, por favor comente aqui nessa issue.

**Comment by elayni** [comment]
Oi, a menção chegou no meu e-mail, mas o convite não. :)

**Comment by itepifanio** [comment]
@cecivieira tem uma pessoa que esqueci de mencionar no corpo da mensagem. Quando puder adiciona @lucasleninsa a organização por favor

**Comment by cecivieira** [comment]
@elayni te enviei um novo e-mail. Por favor, verifica na caixa de spam.

@itepifanio enviei o convite para Lucas.

**Comment by itepifanio** [comment]
@cecivieira tudo certo com a Elayni e o Lucas.

Parece que o convite não foi recebido pela @gabicavalcante. Seria possível reenviá-lo?

**Comment by cecivieira** [comment]
@gabicavalcante reenviei o convite. vê se chegou, por favor

**Comment by rioribeirods** [comment]
@cecivieira pode reenviar para mim também?

**Comment by cecivieira** [comment]
@rioribeirods reenviado =)
