### ISSUE TITLE
Verificar possibilidade da APyB parcelar patrocínio

### ISSUE THREAD

**Issue by itepifanio** [pythonNordeste/organizacao-pyne-2024#40]
Um possível patrocinador levantou a possibilidade de parcelar uma cota de patrocínio em vários boletos. A APyB ficou de verificar junto ao pessoal de contabilidade como isso poderia ser feito e se isso geraria juros adicionais para quem parcela.

O processo normalmente utiliza-se da emissão de uma única nota fiscal e a transferência de recursos é feita diretamente pela empresa a APyB. Para esse caso não fica claro como esse processo poderia incluir o parcelamento do valor da nota fiscal, ou se várias notas fiscais teriam que ser expedidas.

**Comment by itepifanio** [comment]
@cecivieira acredito que ainda seja positivo verificar essa possibilidade, entretando o patrocinador que solicitou isso irá pagar integralmente.

**Comment by cecivieira** [comment]
@itepifanio temos essas orientações:
https://apyb.python.org.br/associados/guias/como-organizar-eventos/#o-patrocinador-quer-parcelar-o-patrocinio-e-possivel
