### ISSUE TITLE
Revisar comunicação com os autores dos trabalhos

### ISSUE THREAD

**Issue by itepifanio** [pythonNordeste/organizacao-pyne-2024#45]
Revisar o template da carta de aceite e rejeição para os autores

**Comment by emillyhorta** [comment]
*Carta de Rejeição*


Olá {participante.nome}, 

Esperamos que esteja bem. Gostaríamos de agradecer pelo esforço e dedicação dedicados à elaboração da palestra "{trabalho.titulo}" recentemente submetida. Agradecemos sinceramente o tempo e energia investidos.
 
Infelizmente sua atividade não foi uma das selecionadas para a grade da Python Nordeste 2024.  
 
Cada ano nós recebemos muitas submissões, e esse ano não foi diferente. A quantidade e  
qualidade das propostas recebidas foram extraordinárias, mas infelizmente nós temos apenas  
alguns slots. 
 
Esperamos que ainda assim você decida participar da Python Nordeste 2024!  

Além de ser uma conferência fantástica, o evento ainda conta com espaços para que você  
possa divulgar o seu material, seja através das "palestras relâmpago" que consistem em  
palestras de até 5 minutos submetidas na hora do evento pelos participantes, 
seja através dos "espaços abertos" uma sala dedicada para discussões e conversas  
mais informais, também preenchida durante o evento. 
 
Se você planeja participar, inscreva-se em https://www.even3.com.br/python-nordeste-2024/  

Se você tiver qualquer dúvida, comentário ou feedback, por favor contate-nos através de  
nordeste@python.org.br 
 
Em nome da equipe Python Nordeste, agradecemos mais uma vez a sua submissão!


*Carta de Aceite*

Olá, {participante.nome} 
 
Esperamos que esteja bem. Gostaríamos de expressar nossos sinceros agradecimentos pela palestra recentemente submetida que teve por tema "{trabalho.titulo}". Nós estamos felizes em informar que sua palestra foi aceita e irá compor a grade do evento Python Nordesete 2024 
 
Pedimos que leia o email completo antes de aceitar. 
 
Por favor, confirme a sua participação através de um email para nordeste@python.org.br 
 
Caso não tenhamos devolutivas até 26 de maio de 2024, 23:59:59 horário de brasília nós teremos que selecionar uma outra atividade no lugar. 
 
Ao aceitar participar da Python Nordeste 2024 você deve estar ciente do nosso código de conduta  
(https://github.com/pythonNordeste/codigo-de-conduta). O código de conduta (ou CDC) é aplicado a todos os participantes, incluindo a própria organização.  
 
Parabéns! Nós estamos ansiosos para ver sua atividade na Python Nordeste 2024! 
 
Sua atividade irá acontecer no slot das xx:xxh as xx:xxh. Sugerimos que separe 5 minutos da sua  
atividade para a resposta de perguntas, ou caso o tempo seja todo consumido se disponibilize após a palestra para tirar dúvidas. 
 
Se esse slot não funcionar para você pedimos que nos comunique imediatamente que verificaremos a melhor forma de acomoda-lo no evento.

Em nome da equipe Python Nordeste, agradecemos e te aguardamos no nosso evento!

**Comment by gabicavalcante** [comment]
Pessoal, adaptei um pouco o template para incluir informações sobre os tutoriais e os slots

---
Nós estamos felizes em informar que sua palestra foi aceita e irá compor a grade do evento Python Nordeste 2024.

Pedimos que leia o email completo antes de aceitar.

Por favor, confirme a sua participação através de um email para [nordeste@python.org.br](mailto:nordeste@python.org.br).

Caso não tenhamos devolutivas até 26 de abril de 2024, 23:59:59 horário de Brasília, nós teremos que selecionar uma outra atividade no lugar.

Ao aceitar participar da Python Nordeste 2024 você deve estar ciente do nosso código de conduta (https://github.com/pythonNordeste/codigo-de-conduta). O código de conduta (ou CDC) é aplicado a todos os participantes, incluindo a própria organização.

Parabéns! Nós estamos ansiosos para ver sua atividade na Python Nordeste 2024!

Informaremos seu slot ao longo da semana, com algumas dicas e sugestões para te ajudar a se organizar para esse momento tão esperado.

Caso sua atividade seja um tutorial, você irá receber mais informações sobre o local em breve. Estamos aguardando algumas confirmações para fechar a logística dessa atividade. 

Em nome da equipe Python Nordeste, agradecemos e te aguardamos no nosso evento!
