### ISSUE TITLE
Orçamento de agenda e caneta

### ISSUE THREAD

**Issue by itepifanio** [pythonNordeste/organizacao-pyne-2024#47]

**Comment by diegodiogenes** [comment]
<img width="744" alt="image" src="https://github.com/pythonNordeste/organizacao-pyne-2024/assets/28743137/9f4a828e-7783-4732-b64c-9e06a5c99a7b">


320 Canetas Modelo 101 1 arte impressa Frente e verso ou só frente
1 Cor de impressão R$ 847,00

Prazo de entrega: 03 a 04 dias após pagamento e layout aprovado. 

Obs: Prazo de entrega é para modelos em loja 

se não dispomos do modelo Desejado em Loja, é necessário um prazo maior para a retirada

Orçamento válido por 48hs.

Forma de pagamento para linha de acrílico é 100% antecipado!

420 Canetas Modelo 101 1 arte impressa Frente e verso ou só frente
1 Cor de impressão R$ 1.107,00

Prazo de entrega: 03 a 04 dias após pagamento e layout aprovado. 

Obs: Prazo de entrega é para modelos em loja 

se não dispomos do modelo Desejado em Loja, é necessário um prazo maior para a retirada

Orçamento válido por 48hs.

Forma de pagamento para linha de acrílico é 100% antecipado!

**Comment by diegodiogenes** [comment]
<img width="744" alt="image" src="https://github.com/pythonNordeste/organizacao-pyne-2024/assets/28743137/0e27b7fc-d1cb-4328-b400-89eeed2da1c7">


320 Canetas Modelo 102 1 arte impressa Frente e verso ou só frente
1 Cor de impressão R$ 735,00

Prazo de entrega: 03 a 04 dias após pagamento e layout aprovado. 

Obs: Prazo de entrega é para modelos em loja 

se não dispomos do modelo Desejado em Loja, é necessário um prazo maior para a retirada

Orçamento válido por 48hs.

Forma de pagamento para linha de acrílico é 100% antecipado!




420 Canetas Modelo 102 1 arte impressa Frente e verso ou só frente
1 Cor de impressão R$ 960,00

Prazo de entrega: 03 a 04 dias após pagamento e layout aprovado. 

Obs: Prazo de entrega é para modelos em loja 

se não dispomos do modelo Desejado em Loja, é necessário um prazo maior para a retirada

Orçamento válido por 48hs.

Forma de pagamento para linha de acrílico é 100% antecipado!

**Comment by diegodiogenes** [comment]
<img width="744" alt="image" src="https://github.com/pythonNordeste/organizacao-pyne-2024/assets/28743137/a68c1fd8-950e-43f0-8f29-2ea81c9d2df1">


320 Canetas Modelo 111 1 arte impressa Frente e verso ou só frente
1 Cor de impressão R$ 847,00

Prazo de entrega: 03 a 04 dias após pagamento e layout aprovado. 

Obs: Prazo de entrega é para modelos em loja 

se não dispomos do modelo Desejado em Loja, é necessário um prazo maior para a retirada

Orçamento válido por 48hs.

Forma de pagamento para linha de acrílico é 100% antecipado!




420 Canetas Modelo 111 1 arte impressa Frente e verso ou só frente
1 Cor de impressão R$ 1.107,00

Prazo de entrega: 03 a 04 dias após pagamento e layout aprovado. 

Obs: Prazo de entrega é para modelos em loja 

se não dispomos do modelo Desejado em Loja, é necessário um prazo maior para a retirada

Orçamento válido por 48hs.

Forma de pagamento para linha de acrílico é 100% antecipado!

**Comment by diegodiogenes** [comment]
<img width="744" alt="image" src="https://github.com/pythonNordeste/organizacao-pyne-2024/assets/28743137/0720f537-e616-44b6-8e07-16d2a1ab017c">


320 Caderneta RECICLE - MULTICOLOR - 18 X 15 1 arte impressa Só frente
1 Cor de impressão R$ 3.155,00

Prazo de entrega: 03 a 04 dias após pagamento e layout aprovado. 

Obs: Prazo de entrega é para modelos em loja 

se não dispomos do modelo Desejado em Loja, é necessário um prazo maior para a retirada

Orçamento válido por 48hs.

Forma de pagamento para linha de acrílico é 100% antecipado!


420 Caderneta RECICLE - MULTICOLOR - 18 X 15  1 arte impressa só frente
1 Cor de impressão R$ 4.130,00

Prazo de entrega: 03 a 04 dias após pagamento e layout aprovado. 

Obs: Prazo de entrega é para modelos em loja 

se não dispomos do modelo Desejado em Loja, é necessário um prazo maior para a retirada

Orçamento válido por 48hs.

Forma de pagamento para linha de acrílico é 100% antecipado!

**Comment by diegodiogenes** [comment]
<img width="744" alt="image" src="https://github.com/pythonNordeste/organizacao-pyne-2024/assets/28743137/72f1c8a4-180f-40e8-b950-1eb4e75d8215">


320 MOLESKINE - couro Sintético  - 14,4 x 8,8 x 1,4cm 1 arte impressa Só frente
1 Cor de impressão R$ 2.817,00

Prazo de entrega: 03 a 04 dias após pagamento e layout aprovado. 

Obs: Prazo de entrega é para modelos em loja 

se não dispomos do modelo Desejado em Loja, é necessário um prazo maior para a retirada

Orçamento válido por 48hs.

Forma de pagamento para linha de acrílico é 100% antecipado!


420 MOLESKINE - couro Sintético  - 14,4 x 8,8 x 1,4cm  1 arte impressa só frente
1 Cor de impressão R$ 3.677,00

Prazo de entrega: 03 a 04 dias após pagamento e layout aprovado. 

Obs: Prazo de entrega é para modelos em loja 

se não dispomos do modelo Desejado em Loja, é necessário um prazo maior para a retirada

Orçamento válido por 48hs.

Forma de pagamento para linha de acrílico é 100% antecipado!

**Comment by diegodiogenes** [comment]
<img width="744" alt="image" src="https://github.com/pythonNordeste/organizacao-pyne-2024/assets/28743137/f742f691-3385-4ef0-89ae-58bf93f9e2bb">


320 mini MOLESKINE - couro Sintético - 10,3 x 7,4 x 1,5 cm 1 arte impressa Só frente
1 Cor de impressão R$ 2.307,00

Prazo de entrega: 03 a 04 dias após pagamento e layout aprovado. 

Obs: Prazo de entrega é para modelos em loja 

se não dispomos do modelo Desejado em Loja, é necessário um prazo maior para a retirada

Orçamento válido por 48hs.

Forma de pagamento para linha de acrílico é 100% antecipado!




420 mini MOLESKINE - couro Sintético - 10,3 x 7,4 x 1,5 cm  1 arte impressa só frente
1 Cor de impressão R$ 3.017,00

Prazo de entrega: 03 a 04 dias após pagamento e layout aprovado. 

Obs: Prazo de entrega é para modelos em loja 

se não dispomos do modelo Desejado em Loja, é necessário um prazo maior para a retirada

Orçamento válido por 48hs.

Forma de pagamento para linha de acrílico é 100% antecipado!

**Comment by itepifanio** [comment]
Perfeito, muito obrigado @diegodiogenes !
