### ISSUE TITLE
Orçamento de chaveirinho

### ISSUE THREAD

**Issue by itepifanio** [pythonNordeste/organizacao-pyne-2024#48]
A ideia é dar um toque regional ao kit do participante, utilizando os chaveirinhos com areia colorida (exemplo abaixo). A imagem poderia ser de um cajú ou uma cobrinha, utilizando as cores da identidade visual da Python Nordeste.

![R](https://github.com/pythonNordeste/organizacao-pyne-2024/assets/6730205/3feceb86-7675-4730-9489-01ffa7df4a92)

**Comment by PatriciaSilvaRecife** [comment]
Quem ficou responsável e qual o prazo?

**Comment by itepifanio** [comment]
@PatriciaSilvaRecife o Matheus ficou responsável por essa issue. Acredito que ele não esteja na organização e por isso não consegui atribuir essa tarefa a ele.
