### ISSUE TITLE
Usar o OTP para verficação de dois fatores do e-mail

### ISSUE THREAD

**Issue by allythy** [pythonNordeste/organizacao-pyne-2024#49]
**Contexto**
Atualmente a  autenticação de dois fatores está sendo feita por um número que enviado ao celular de uma pessoa que vinculou a conta da Python Nordeste.

**Problema**
Todas vez que é para fazer login no email é necessário falar com a pessoa que vinculou o  número do celular a conta, para solicitar os códigos.

**Possível solução**
Usar para autenticação de dois fatores o  OTP(one-time password), que irá gerar um código único de acesso para fazer o login no email.  Como usamos gerenciador de senhas, e o mesmo tem suporte OTP, poderíamos fazer essa migração

**Comment by allythy** [comment]
@cecivieira

**Comment by cecivieira** [comment]
@allythy o código gerado não é para o celular de 1 pessoa, mas para quem fez o 1. login no celular na conta do e-mail .
O OTP esbarra em uma problemátiva semelhante, pois apenas quem tiver acesso ao gerenciador de senhas tem acesso ao código para a segunda etapa de autenticação.

Mas, não vejo problema em configurarmos o Bitwarden para OTP no e-mail da comunidade.

**Comment by itepifanio** [comment]
Fechando essa issue. Movi a discussão para [o repositório da APyB](https://github.com/apyb/comunidade/discussions/130#discussioncomment-10326119)
