### ISSUE TITLE
Arte para campanha de doação

### ISSUE THREAD

**Issue by allythy** [pythonNordeste/organizacao-pyne-2024#50]
Valor: 5 mil reais, uma conta bronze
chave pix: doacao@grupyrn.org

Exemplo da campanha de doação da MiniDebConf:
https://x.com/debianbrasil/status/1749096625018921218
https://x.com/debianbrasil/status/1759347641970815107

**Comment by lucasleninsa** [comment]
Oi, segue o link

https://drive.google.com/file/d/1UQQCm_H3I4_vq_ik-2qrHxzfvvEQUKC-/view?usp=drive_link

**Comment by itepifanio** [comment]
Muito obrigado @lucasleninsa, ficou ótimo como sempre!
