### ISSUE TITLE
Template figma para divulgação das palestras PyNE

### ISSUE THREAD

**Issue by itepifanio** [pythonNordeste/organizacao-pyne-2024#52]

**Comment by lucasleninsa** [comment]
Olá, segue o link do template:
https://www.figma.com/design/f4OyB0qfkm8YTIWqNpZ7jl/PYTHON-NORDESTE-24?node-id=45-359&t=tE9n7nZu6x7vFhQH-1

Segue o link do vídeo explicando como utilizar:
https://drive.google.com/file/d/1udNtVLoVlwBrKLuJug34RnDuLUzS4O8X/view?usp=sharing

**Comment by itepifanio** [comment]
Muito obrigado, Lucas. Fechando essa task :)
