### ISSUE TITLE
Fila de artes

### ISSUE THREAD

**Issue by itepifanio** [pythonNordeste/organizacao-pyne-2024#73]
| Design | Data limite | Status |
| -------- | ------------- | ---------- |
| Design da camisa do evento | 07/06/2024 | Feito |
| Arte para informar virada de lote | 09/06/2024 | Feito  |
| Design da cartela de adesivos | 17/06/2024 | Feito |
| Design do backdrop e banner de boas vindas | 21/06/2024 | Feito |
| Design da ecobag | 28/06/2024 | Feito |
| Design do copo | 05/07/2024 | Feito |
| Design do crachá | 12/07/2024 | Feito | 

## Design da camisa do evento

Serão desenvolvidas duas camisas, com a mesma arte, mas com cores diferentes. Uma cor será distribuida para o público geral e a outra será distribuída para a equipe de Código de Conduta (CDC), para destacar eles.

A arte deverá ter no máximo 4 cores e conterá a logo de um dos patrocinadores nas costas

## Arte para informar virada de lote

Queremos informar que o último lote irá começar a ser vendido no dia 14/06/2024 e que as vendas seguirão até o dia 07/07/2024. Pode utilizar o seguinte template de mensagem para elaborar essa arte:

```
🎟️ Última Chance! Último Lote de Ingressos 🎟️

Atenção, galera! A virada do último lote de ingressos está chegando! 🚀 No dia 14/06/2024, começaremos a vender o último lote do evento. As vendas continuarão até o dia 07/07/2024, mas não deixe para a última hora! 🕛

Garanta já o seu lugar e não fique de fora dessa experiência incrível! 🔥✨
```

## Design da cartela de adesivos

A cartela de adesivos deve ser desenvolvida em tamanho A6 (10.5cm x 14.8cm). Iremos utilizar a [nerd stickers](https://www.nerdstickers.com.br/stickers/adesivos-personalizados/cartela-de-adesivos/) para tal, as orientações do site deles de formato de imagem devem ser seguidos

## Design do backdrop e banner de boas vindas

O backdrop tem 5m de largura e 2 metros de altura, ficará nesse espaço:

![IMGP5975](https://github.com/pythonNordeste/organizacao-pyne-2024/assets/6730205/72275551-fafc-4d10-afd1-78ea60d8afcc)

Já o banner mostrará ao usuário o local do evento, será colocado aqui, na entrada do local. (Ver com @diegodiogenes o tamanho do banner que foi orçado com a vital gráfica)

![IMG_20231112_174648](https://github.com/pythonNordeste/organizacao-pyne-2024/assets/6730205/3b3bd8f9-5040-4641-87f2-e4c96476c718)

## Design da ecobag

[Bolsa em algodão cru no tamanho 30x40](https://www.caicobrindes.net.br/bolsas/bolsas-em-algodao/bolsas-em-tecido-algodao-cru-30x40cm-personalizada-em-1-cor), a arte deve conter apenas uma cor

## Design do copo

Copo de 400ml sem tampa da [Meu eco copo](https://www.meucopoeco.com.br/), a arte deve conter apenas uma cor e deve respeitar a estrutura pedida pelo site

## Design do crachá

O crachá tem que conter os patrocinadores em tamanho maior: Python Software Foundation e Save In Cloud
Além dos apoiadores que podem ter logo em tamanho reduzido:  Sebrae, Sebraelab e IMD+UFRN em tamanho menor. Seguem as logos que devem ser adicionadas:

![image](https://github.com/user-attachments/assets/0a72d87e-7a1f-4e27-90fa-25d80346e06a)

![image](https://github.com/user-attachments/assets/cc866abd-5dc1-4c81-83c0-36f4792d319b)

O crachá deve ter espaço para as pessoas colocarem seu nome e pronomes. Não iremos utilizar adesivos igual a edição 2022 fez, mas pode utilizar a estrutura deles como base:

![photo_4958875262238436637_y](https://github.com/user-attachments/assets/fddec3b9-6af6-4836-a576-283086fd04b8)

**Comment by lucasleninsa** [comment]
Olá, segue o link dos adesivos https://drive.google.com/drive/folders/1cLHLZr1a83g9PcWiz2OaStQ134q8Qpsf?usp=drive_link

**Comment by lucasleninsa** [comment]
Olá, segue o link do backdrop: https://drive.google.com/drive/folders/1g9Ztsgyka_j3vGdwMAPNKHdTyNyACLsa

**Comment by lucasleninsa** [comment]
Olá, segue o link do copo: https://drive.google.com/drive/folders/1UfXSGxmbusdJ_3jYf_ctD4XPEU40E5ny

**Comment by lucasleninsa** [comment]
Olá, segue o link da ecobag: https://drive.google.com/drive/folders/1iIYyqN1sD_pY-gZpJ7uzE4Wa62tBsfwT?usp=drive_link

**Comment by lucasleninsa** [comment]
Olá, segue o link do crachá: https://drive.google.com/drive/folders/1Qg_IyIGyXtB6ArBvlll5RJ2jq6_6YQy6
