### ISSUE TITLE
Escolher plataforma de submissão de atividades

### ISSUE THREAD

**Issue by itepifanio** [pythonNordeste/organizacao-pyne-2024#9]
O pretalx, utilizado em anos anteriores, é pago. Vamos analisar mais algumas ferramentas de submissão de atividades (podem considerar ferramentas open source que possamos realizar o deploy).

- [ ] Levantar preço, pros e contras de ferramentas
- [ ] Escolher ferramenta
- [ ] Opcionalmente: realizar o deploy da ferramenta

**Comment by allythy** [comment]
Vamos usar a even3: https://www.even3.com.br/

 - Com taxa 9,49% do valor do ingresso. 
 - R$808 para ter a submissão de atividades.
