### ISSUE TITLE
Inserção do link do formulário de denuncia do CDC no site

### ISSUE THREAD

**Issue by AndressaLF** [pythonNordeste/organizacao-pyne-2024#97]
O link do formulário de denuncia do CDC ainda não foi adicionado na pagina do Codigo de Conduta do site, acredito que seria interessante adicionar ele o mais perto possível do dia do evento, segue o endereço:

 **https://forms.gle/5i9mG4AFKH2QMNNc9**

**Comment by itepifanio** [comment]
Criei [o PR](https://github.com/pythonNordeste/pyne2024/pull/42/files), irei aceitar na sexta de manhã ou quinta a noite.
